version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    volumes:
      - ./policy.rego:/config/policy.rego
    command:
      - "run"
      - "--server"
      - "--addr=:8181"
      - "/config/policy.rego"